# COLORS
PRIMARY_COLOR = "#42659d"
ACCENT_COLOR = "#bfd5e3"
ACCENT_2_COLOR = "#7ea6d7"
LIGHT_WHITE = "#d7e6e1"
TEXT_COLOR_WHITE = "#ffffff"
TEXT_EDITOR_BG = "#E0E0E0"
LONG_SENTENCE_HIGHLIGHT_COLOR_MID = "#ffe8a8"
LONG_SENTENCE_HIGHLIGHT_COLOR_HIGH = "#d15f26"
SEARCH_RESULT_HIGHLIGHT_COLOR = "yellow"
CURRENT_SEARCH_RESULT_HIGHLIGHT_COLOR = "orange"

# COLOR PALLETE FOR CLOSE WORDS
CLOSE_WORDS_PALLETE = [
    '#8B0000',  # Dark Red
    '#FF0000',  # Red
    '#0000FF',  # Red
    '#8B008B',  # Dark Magenta
    '#FF4500',  # Orange Red
    '#CD5C5C',  # Indian Red
]