class FontAwesomeIcons:
    file = '\uf15b'
    folder = '\uf07b'
    floppy_disk = '\uf0c7'
    rotate_left = '\uf2ea'
    rotate_right = '\uf2f9'
    file_export = '\uf56e'
    file_import = '\uf56f'
    gears = '\uf013'
    wrench = '\uf0ad'
    pallete = '\uf53f'
    book = '\uf02d'
    question_circle = '\uf059'
    magnifying_glass = '\uf002'
    rotate = '\uf2f1'
    download = '\uf019'
    link = '\uf0c1'
    link_broken = '\uf127'
