GRAMMAR_ERROR_TYPE_MISSPELLED_WORD = 'MISSPELLED_WORD'
GRAMMAR_ERROR_NON_LITERAL_WORD = 'GRAMMAR_ERROR_NON_LITERAL_WORD'
GRAMMAR_ERROR_TOMU_INSTEAD_OF_TO = 'GRAMMAR_ERROR_TOMU_INSTEAD_OF_TO'
GRAMMAR_ERROR_S_INSTEAD_OF_Z = 'GRAMMAR_ERROR_S_INSTEAD_OF_Z'
GRAMMAR_ERROR_Z_INSTEAD_OF_S = 'GRAMMAR_ERROR_Z_INSTEAD_OF_S'
GRAMMAR_ERROR_TYPE_WRONG_Y_SUFFIX = 'WRONG_Y_SUFFIX'
GRAMMAR_ERROR_TYPE_WRONG_YSI_SUFFIX = 'WRONG_YSI_SUFFIX'
GRAMMAR_ERROR_TYPE_WRONG_I_SUFFIX = 'WRONG_I_SUFFIX'
GRAMMAR_ERROR_TYPE_WRONG_ISI_SUFFIX = 'WRONG_ISI_SUFFIX'

# NON LITERAL WORDS WITH THEIR CORRECT REPLACEMENTS
NON_LITERAL_WORDS = {
    "môžme": "môžeme",
    "môžťe": "môžete",
    "tohoto": "tohto"
}
