name: Generate licence check report
description: Chech licences of dependencies
# Schema: https://json.schemastore.org/github-action.json

inputs:
  python_version:
    description: 'Os to run against'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Check package licences
      id: license_check_report
      uses: pilosus/action-pip-license-checker@v2
      with:
        requirements: 'requirements-all.txt'
        fail: 'Other'
        exclude: '(?i)^(pylint|aio[-_]*).*'
        report-format: 'json-pretty'
        formatter: '%-65s %-65s %-20s %-40s'
        totals: true
        headers: true
        verbose: 1
    - name: Save licence check report
      env:
        RESULT: ${{  steps.license_check_report.outputs.report }}
      shell: bash
      if: ${{ !cancelled() }}
      run: echo "$RESULT" > license-report.json
    - name: Upload license check report artifact
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: license-report-python-${{inputs.python_version}}
        path: license-report.json