name: Setup hector enviroment
description: Setup python and dependencies
# Schema: https://json.schemastore.org/github-action.json

inputs:
  python_version:
    description: 'Os to run against'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python_version}}
        cache: 'pip'
        check-latest: true
    - name: Install GCC for linux
      uses: egor-tensin/setup-gcc@v1.3
      if: matrix.os == 'ubuntu-latest'
    - name: Install hunspell requirements for linux
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: sudo apt install -y autoconf libtool gettext autopoint
    - name: Symlink tcl 8.6 for macos-13
      shell: bash
      if: matrix.os == 'macos-13' && inputs.python_version == '3.10'
      run: |
        ln -s /Users/runner/hostedtoolcache/PyPy/3.7.13/x64/lib/libtcl8.6.dylib /usr/local/lib/libtcl8.6.dylib
        ln -s /Users/runner/hostedtoolcache/PyPy/3.7.13/x64/lib/libtk8.6.dylib /usr/local/lib/libtk8.6.dylib
    - name: Install requirements for macOS
      shell: bash
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-13' || matrix.os == 'macos-12'
      run: brew install automake autoconf libtool
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        pip freeze > requirements-all.txt