# This workflow will install Python dependencies, run tests and lint with a single version of Python, then build with nuitka
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Nuitka build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] #FIXME: windows-latest, macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1.3
      - name: Install hunspell
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libhunspell-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: develop
          script-name: hector.py
          onefile: true
          enable-plugin: tk-inter
          include-package: ttkthemes
          include-package-data: ttkthemes
          include-module: fsspec.implementations.github
          include-data-dir: images=images


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.bin
