# This workflow will install Python dependencies, run tests and lint with a single version of Python, then build with nuitka
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Nuitka build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install GCC for linux
        uses: egor-tensin/setup-gcc@v1.3
        if: matrix.os == 'ubuntu-latest'
      - name: Install hunspell dependencies for linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y autoconf libtool gettext autopoint
      - name: Install hunspell requirements for macOS
        if: matrix.os == 'macos-latest'
        run: brew install automake autoconf libtool
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: develop
          script-name: hector.py
          onefile: true
          enable-plugins: tk-inter
          include-package: ttkthemes,cacheman,hunspell
          include-package-data: ttkthemes,hunspell
          include-module: fsspec.implementations.github
          include-data-dir: images=images,data_files=data_files
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.bin
            build/*.exe
            build/*.app/**/*
          compression-level: 0 #NUITKA ALREADY COMPRESSES
      - name: Upload binary to release
        if: |
          github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hector.*
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
